#! /bin/bash
### BEGIN INIT INFO
# Provides:          ipop-vpn
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start IPOP Tincan & Controller
### END INIT INFO
# /opt/ipop-vpn/ipop-systemd {start|stop|restart}
# or
# sudo systemctl {start|stop|restart} ipop

INSTALLATION_DIR=/opt/ipop-vpn

ipop_start() {
    cd "$INSTALLATION_DIR"
    touch /tmp/ipop-tincan-pid
    ./ipop-tincan &
    echo $! > /tmp/ipop-tincan-pid
    touch /tmp/ipop-controller-pid
    source ipop-venv/bin/activate
    python3 -m controller.Controller -c /etc/opt/ipop-vpn/config.json &
    echo $! > /tmp/ipop-controller-pid 
}

ipop_stop() {
    kill -2 $(head -n 1 /tmp/ipop-controller-pid)
    kill -2 $(head -n 1 /tmp/ipop-tincan-pid)
    rm /tmp/ipop-tincan-pid
    rm /tmp/ipop-controller-pid 
}

ipop_abort() {
    kill -9 $(head -n 1 /tmp/ipop-tincan-pid)
    kill -9 $(head -n 1 /tmp/ipop-controller-pid)
    rm /tmp/ipop-tincan-pid
    rm /tmp/ipop-controller-pid 
}

case "$1" in
  start)
    ipop_start
    ;;
  stop)
    ipop_stop
    ;;
  restart)
    ipop_stop
    ipop_start
    ;;
  reload)
    ipop_abort
    ipop_start
    ;;
  abort)
    ipop_abort
    ;;
  *)
    echo "Usage: /opt/ipop-vpn/ipop-systemd {start | stop | restart}"
    exit 1
    ;;
esac

exit 0
