#!/bin/bash

cd /opt/ipop-vpn
pip3 install virtualenv
virtualenv ipop-venv
source ipop-venv/bin/activate
pip3 install psutil sleekxmpp requests
deactivate
systemctl daemon-reload
systemctl enable ipop
