name: ipopvpn
version: '0.993'
summary: IPOP VPN, IP Over P2P
description: |
  IPOP (IP-Over-P2P) is an open-source user-centric software virtual network allowing end users to define and create their own virtual private networks (VPNs). IPOP virtual networks provide end-to-end tunneling of IP or Ethernet over Tincan links setup and managed through a control API to create various software-defined VPN overlays.
grade: devel
confinement: devmode
base: core18

apps:
  tincan:
    command: ipop-tincan
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch
      - openvswitch-support
  controller:
    command: run-controller
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch
      - openvswitch-support
  ovs-vswitchd:
    command: ovs-wrapper $SNAP/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor --system-id=random start
    stop-command: ovs-wrapper $SNAP/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
  ovsdb-server:
    command: ovs-wrapper $SNAP/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor --system-id=random start
    stop-command: ovs-wrapper $SNAP/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
  ovs-vsctl:
    command: ovs-wrapper $SNAP/bin/ovs-vsctl
    plugs:
      - network
  ovs-appctl:
    command: ovs-wrapper $SNAP/bin/ovs-appctl
    plugs:
      - network
  ovs-ofctl:
    command: ovs-wrapper $SNAP/bin/ovs-ofctl
    plugs:
      - network
  ovs-dpctl:
    command: ovs-wrapper $SNAP/bin/ovs-dpctl
    plugs:
      - network

parts:
  setup:
    plugin: python
    python-version: python3
    python-packages: [psutil, requests, sleekxmpp]
  tincan:
    source: https://github.com/ipop-project/Tincan.git
    source-commit: ac12c428808f417a9b4f9a8389e43d7fbb3ae6d0
    plugin: dump
    stage-packages: [iproute2, openvswitch-switch, bridge-utils, openvswitch-common, net-tools]
    stage: [trunk, external]
  3rd-party-libs:
    source: https://github.com/ipop-project/3rd-Party-Libs.git
    source-branch: rpi3-arm7
    plugin: dump
    organize:
        debug: external/3rd-Party-Libs/debug
        release: external/3rd-Party-Libs/release
    stage: [external/3rd-Party-Libs/debug, external/3rd-Party-Libs/release]
  make-tincan:
    plugin: make
    artifacts: [../out/release/armv7l/ipop-tincan]
    source-subdir: ../../../stage/trunk/build/
    organize:
        ../out/release/armv7l/ipop-tincan: ipop-tincan
    build-packages: [make, gcc, libssl-dev, python3, python3-pip, python3-dev]
    build-attributes: [keep-execstack]
    after: [3rd-party-libs, tincan]
  controller:
    source: https://github.com/ipop-project/Controllers.git
    source-commit: d16c3810f1fb2d6335fbdebafff9211300e73192
    plugin: dump
    stage-packages: [iproute2, openvswitch-switch, bridge-utils, openvswitch-common, net-tools]
    after: [tincan]
    stage: [controller]
  patches:
    source: snap/patches/
    plugin: dump
    organize:
      '*' : patches/
    prime:
      - -*
  openvswitch:
    source: http://openvswitch.org/releases/openvswitch-2.10.0.tar.gz
    plugin: autotools
    build-packages:
      - libssl-dev
      - libnuma-dev
      - libcap-ng-dev
      - libpcap-dev
      - libunbound-dev
      - python-all
      - python-six
      - python-setuptools
    stage-packages:
      - uuid-runtime
    configflags:
      - "--localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common"
      - "--sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/etc"
    after:
      - patches
    prepare: |
      # Apply patches
      for patch in ${SNAPCRAFT_STAGE}/patches/openvswitch/*.patch; do
        echo "Applying $(basename "$patch") ..."
        patch \
          --batch \
          --forward \
          --strip 1 \
          --input "$patch"
        echo
      done
  wrapper:
    source: conf
    plugin: dump
    stage-packages: [iproute2, openvswitch-switch, bridge-utils, openvswitch-common, net-tools]
