#!/bin/bash

# Usage: wget -O - https://raw.githubusercontent.com/ipop-project/Release-Management/master/Deployment/linux/installer | /bin/bash

ASSISTANT_URL=https://raw.githubusercontent.com/ipop-project/Release-Management/master/Deployment/linux/assistant

INSTALLATION_DIR=/opt/ipop

MSG_GENERAL_NEED_ROOT="Run with Root Privilege"

function i_am_root(){
	return $EUID
}
function force_root(){
	if ! i_am_root; then
		echo "$MSG_GENERAL_NEED_ROOT"
		exit 5
	fi
}

force_root

mkdir -p "$INSTALLATION_DIR" 2>/dev/null
cd "$INSTALLATION_DIR"
wget "$ASSISTANT_URL"

#if [ "$(md5sum $ASSISTANT_BINARY_NAME | awk '{print $1}')" == "$ASSISTANT_BINARY_MD5" ]; then
#	echo $MSG_INSTALL_ASSISTANT_CHECKSUM_FAILED
#	exit 3
#fi

chmod +x assistant

./assistant install
