#!/bin/bash

# Usage: wget -O - http://raw.githubusercontent.com/ipop-project/Release-Management/master/Deployment/linux/installer | /bin/bash

IPOP_URL=https://raw.githubusercontent.com/ipop-project/Release-Management/dev/Deployment/linux/ipop

INSTALLATION_DIR=/opt/ipop

MSG_GENERAL_NEED_ROOT="
Run with Root Privilege
Make sure you have already switched to interactive root shell using 'sudo -i' before running the above command. Running it with just adding 'sudo' to the beginning is not enough."

function i_am_root(){
	return $EUID
}

function force_root(){
	if ! i_am_root; then
		echo "$MSG_GENERAL_NEED_ROOT"
		exit 5
	fi
}

force_root

mkdir -p "$INSTALLATION_DIR" 2>/dev/null
cd "$INSTALLATION_DIR"
wget -N "$IPOP_URL"
chmod +x ipop
./ipop install
