#!/bin/bash

cd /opt/ipop-vpn
python3 -m pip --no-cache-dir install virtualenv
virtualenv --python=python3.6 ipop-venv
source ipop-venv/bin/activate
python3 -m pip --no-cache-dir install psutil==5.6.3 sleekxmpp==1.3.3 requests==2.21.0 simplejson==3.16.0 ryu==4.30
deactivate
systemctl daemon-reload
systemctl enable ipop
