#!/bin/bash

cd /opt/ipop-vpn
pip3 --no-cache-dir install virtualenv
virtualenv ipop-venv
source ipop-venv/bin/activate
pip3 install --no-cache-dir psutil sleekxmpp requests simplejson
deactivate
systemctl daemon-reload
systemctl enable ipop
