#!/bin/sh

cat <<! > ipop-vpn/DEBIAN/control
Package: ipop-vpn
Name: IPOP-VPN
Version: 18.b7
Maintainer: <ipop@ipop-project.org>
Architecture: $(dpkg --print-architecture)
Homepage: http://ipop-project.org
Depends: python3, python3-pip, iproute2, openvswitch-switch, bridge-utils
Description: Virtual Overlay Networks.
 IPOP (IP-Over-P2P) is an open-source user-centric software virtual network allowing end users to define and create their own virtual private networks (VPNs). IPOP virtual networks provide end-to-end tunneling of IP or Ethernet over Tincan links setup and managed through a control API to create various software-defined VPN overlays.
Tag: P2P Overlay Networking
!

dpkg-deb --build --root-owner-group ipop-vpn .

rm ipop-vpn/DEBIAN/control
